# Generated by Django 4.0.4 on 2022-05-07 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(max_length=50)),
                ('lang', models.CharField(choices=[('pt', 'Português'), ('es', 'Espanhol'), ('en', 'Inglês')], max_length=2)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='user.user')),
                ('users', models.ManyToManyField(related_name='companies', to='user.user')),
            ],
        ),
    ]
