# Generated by Django 4.0.4 on 2022-05-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('password', 'last_password_redefinition_at')},
        ),
    ]
